[package]
name = "tetris"
version = "0.1.0"
authors = ["G0rocks <huldarh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rodio = "0.11.0"
orbtk = "0.3.1-alpha3"
file = "1.1.2"